#!/bin/sh
lock() {
	i3lock \
		--dpms \
		--ignore-empty-password \
		--no-unlock-indicator \
		--color 000000 \
		--image $HOME/.i3/lockscreen.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
	switch-user)
		lock && gdmflexiserver
		;;
    *)
        echo "Usage: $0
		{lock|logout|suspend|hibernate|reboot|shutdown|switch-user}"
        exit 2
esac

exit 0
